### PR TITLE
Better gitlibs support

### LINKED ISSUE #61: Consider adding a fake git command
If we use a custom build command in `mkCljBin`, it is relatively easy to call some clojure function that invokes git. In that case, the error from clojure is quite cryptic (see #60 )

Consider adding a fake git binary that prints a better error message, and exits with an error

### LINKED ISSUE #108: Manifest file not found error
The following deps.edn doesn't work:
```
{:paths ["src"]
 :deps
 {metrics-clojure/metrics-clojure
  {:git/url "https://github.com/clj-commons/metrics-clojure"
   :deps/root "metrics-clojure-core"
   :git/sha "532fc437e734b049a54cb9a198f201dc5f47328e"}}}
```
Running `nix run github:jlesquembre/clj-nix#deps-lock` gives the following output:
```
{:clojure.main/message
 "Execution error (ExceptionInfo) at clojure.tools.deps.extensions/throw-bad-manifest (extensions.clj:158).\nManifest file not found for metrics-clojure/metrics-clojure in coordinate {:git/url \"https://github.com/clj-commons/metrics-clojure\", :deps/root \"metrics-clojure-core\", :git/sha \"532fc437e734b049a54cb9a198f201dc5f47328e\"}\n",
 :clojure.main/triage
 {:clojure.error/class clojure.lang.ExceptionInfo,
  :clojure.error/line 158,
  :clojure.error/cause
  "Manifest file not found for metrics-clojure/metrics-clojure in coordinate {:git/url \"https://github.com/clj-commons/metrics-clojure\", :deps/root \"metrics-clojure-core\", :git/sha \"532fc437e734b049a54cb9a198f201dc5f47328e\"}",
  :clojure.error/symbol
  clojure.tools.deps.extensions/throw-bad-manifest,
  :clojure.error/source "extensions.clj",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.ExceptionInfo,
    :message
    "Manifest file not found for metrics-clojure/metrics-clojure in coordinate {:git/url \"https://github.com/clj-commons/metrics-clojure\", :deps/root \"metrics-clojure-core\", :git/sha \"532fc437e734b049a54cb9a198f201dc5f47328e\"}",
    :data
    {:lib metrics-clojure/metrics-clojure,
     :coord
     {:git/url "https://github.com/clj-commons/metrics-clojure",
      :deps/root "metrics-clojure-core",
      :git/sha "532fc437e734b049a54cb9a198f201dc5f47328e"}},
    :at
    [clojure.tools.deps.extensions$throw_bad_manifest
     invokeStatic
     "extensions.clj"
     158]}],
  :trace
  [[clojure.tools.deps.extensions$throw_bad_manifest
    invokeStatic
    "extensions.clj"
    158]
   [clojure.tools.deps.extensions$throw_bad_manifest
    invoke
    "extensions.clj"
    153]
   [clojure.tools.deps.extensions$eval514$fn__515
    invoke
    "extensions.clj"
    166]
   [clojure.lang.MultiFn invoke "MultiFn.java" 244]
   [clojure.tools.deps$expand_deps$children_task__682$fn__684$fn__685
    invoke
    "deps.clj"
    406]
   [clojure.lang.AFn applyToHelper "AFn.java" 152]
   [clojure.lang.AFn applyTo "AFn.java" 144]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1990]
   [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1990]
   [clojure.lang.RestFn invoke "RestFn.java" 425]
   [clojure.lang.AFn applyToHelper "AFn.java" 156]
...
```

### PR DESCRIPTION
**Pull request by mjmeintjes**
This adds support for dependencies that specify :git/tag and shortened :git/sha

Also fixes #108 "Manifest not found error" for dependencies using :deps/root

Changes:
- Pre-calculate information about rev ancestors and store in lock file
- Bump lock file version
- Store git repo info in nix store under ${git-dir}/revs/REV
- Add fake git command to provide git tags and rev ancestor information at build time using the git repo info stored in ${git-dir}/revs/REV (fixes #61)

### CODE REVIEW

File: src/cljnix/git.clj [hunk 1]
```diff
@@ -0,0 +1,53 @@
+;; Copied from https://github.com/clojure/tools.gitlibs
```
Comment (jlesquembre) [inline src/cljnix/git.clj:1]: Do we really need to copy the file? Notice that `tools.gitlibs` is already a transitive dependency, in fact, we already use it on another places, like here:
https://github.com/jlesquembre/clj-nix/blob/545e7f55c9cb014123b2b3261385f1561d308402/src/cljnix/utils.clj#L10
https://github.com/jlesquembre/clj-nix/blob/545e7f55c9cb014123b2b3261385f1561d308402/src/cljnix/utils.clj#L177

File: pkgs/fakeGit.nix [hunk 2]
```diff
@@ -0,0 +1,9 @@
+{
+  pkgs,
+  ...
+}:
+
+pkgs.writers.writePython3Bin "git"
```
Comment (jlesquembre) [inline pkgs/fakeGit.nix:6]: This reminds me I wanted to add a `writeBabashkaScript` helper to nixpkgs.

File: pkgs/fake-git.py [hunk 3]
```diff
@@ -0,0 +1,58 @@
+import argparse
```
Comment (jlesquembre) [inline pkgs/fake-git.py:1]: Would be possible to rewrite this script with babashka? 
I'm not a python fan, I'd prefer to use clojure where possible.
In fact, I want to start replacing the bash script in the project with babashka (but that's something to do in the future)

Would you like to rewrite it? If you aren't interested on doing it, we can merge this PR to another branch, and I'll rewrite it before merging it to the main branch.

**Review by jlesquembre — COMMENTED** [review]
Thanks a lot for your PR! I took a quick look and added some comments. I want to take a second look with more calmness, but overall it looks good. :)

I like the fake git approach. It will probably allow us to remove this function:

https://github.com/jlesquembre/clj-nix/blob/545e7f55c9cb014123b2b3261385f1561d308402/src/cljnix/utils.clj#L252

But that's something to tackle on a different PR

File: src/cljnix/git.clj (hunk 1 above)
Comment (mjmeintjes) [reply src/cljnix/git.clj:1]: I copied this file because the `ancestor?` and `run-git` functions are private in `tools.gitlibs`, not sure if there is a better way to call those functions.

File: pkgs/fake-git.py (hunk 3 above)
Comment (mjmeintjes) [reply pkgs/fake-git.py:1]: I also prefer babashka, and initially tried using it, but the build froze and I couldn't figure out why. I suspected that it might have something to do with the JAVA_TOOL_OPTIONS environment variable that clj-nix sets, but I didn't investigate it a more.

I'm happy to have another look.

File: src/cljnix/git.clj (hunk 1 above)
Comment (jlesquembre) [reply src/cljnix/git.clj:1]: Maybe invoke it with `(#'gli/run-git ...)`? 
https://groups.google.com/g/clojure/c/Mi277rszUs0/m/G9Q0ua9nM1EJ

File: pkgs/fake-git.py (hunk 3 above)
Comment (jlesquembre) [reply pkgs/fake-git.py:1]: If you can try, that would be nice :)
There have been some updates to Babashka in Nixpkgs. Maybe updating the flake.lock file could help.
I'm also okay with wrapping Babashka to (un)set any environment variables we need.

Comment (mjmeintjes) [reply pkgs/fake-git.py]: I replaced the script with babashka. Just had to run bb with `--classpath=""` to prevent it hanging.

File: src/cljnix/git.clj (hunk 1 above)
Comment (mjmeintjes) [reply src/cljnix/git.clj]: I've removed the git ns and changed the code to call the private gitlibs.impl/ancestor? function.

**Comment by mjmeintjes** [comment]
Can you have a look at the tests in fake_git_test.clj to see why they are failing? They pass when I run them locally, and I don't know enough about Github Actions to figure out why they are failing.

```
❯ kaocha
       unit:   100% [==================================================] 13/13
integration:   100% [==================================================] 15/15
28 tests, 61 assertions, 0 failures.
```


I could also just comment out the tests.

**Comment by jlesquembre** [comment]
@mjmeintjes thanks, let's keep the tests, I'll try to find why are failing only on CI

File: pkgs/fake_git.clj [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+        (if (get-in rev-d ["ancestor?" ancestor])
+          [0]
+          [1]))
+
+      :else
+      (throw (Exception. (str "fake-git: unknown git command - " args))))))
+
+(defn -main []
+  (let [res (result (cli/parse-args *command-line-args*))]
+    (doseq [line res]
```
Comment (jlesquembre) [inline pkgs/fake_git.clj:54]: Why `doseq`? Looks like it's only used to print the vector of string in multiple lines


Can we update `result` to return 
`{:exit 0 :out []}` ,
 `{:exit 1 :out []}`,
 `{:exit 0 :out ["v0.0.1" "v0.0.2"]}`, ...

And then do a `(->> res :out (string/join "\n") println)`

File: test/integration/fake_git_test.clj [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+   [cljnix.nix :as nix]
+   [matcher-combinators.test]
+   [clojure.java.shell :as sh]
+   [clojure.string :as str])
+  )
+
+(defn- run-fake-git [project-dir cmd]
+  (sh/sh
+   "bash" "-c"
+   (str "nix run .#fake-git -- --git-dir " project-dir " " cmd)))
```
Comment (jlesquembre) [inline test/integration/fake_git_test.clj:15]: I want to avoid calling external programs in clojure tests. For those cases we can use `bats`, but since we are invoking a bb script, why not calling that code directly from clojure?

Could you update the babashka script to have 2 main functions? e.g.: `main` and `main*`

`main` is the real entry point when invoked with babashka, it should be quite minimal and invoke `main*`
`main*` returns only data, and we call this function from  the clojure tests.

In `deps.edn`, we can add `pkgs` in the `:test {:extra-pahts [...] }`

File: pkgs/fake_git.clj (hunk 4 above)
Comment (mjmeintjes) [reply pkgs/fake_git.clj]: I made these changes as suggested.

File: test/integration/fake_git_test.clj (hunk 5 above)
Comment (mjmeintjes) [reply test/integration/fake_git_test.clj]: I changed the fake-git script and tests as suggested, tests pass on my side.

**Comment by mjmeintjes** [comment]
It seems that the `extra-pkgs/babashka/deps-lock.json` needs to be regenerated to work with the new lock file version. How do I do this?

**Comment by jlesquembre** [comment]
@mjmeintjes thanks, on my local babashka clone I run 
```
nix run ~/projects/clj-nix#deps-lock -- --lein --deps-exclude resources/META-INF/babashka/deps.edn
```

I'm going to update it

**Comment by jlesquembre** [comment]
I updated the lock files, and updated `calc-ancestors` to return a `sorted-map`, I'm waiting for CI to finish before merging it.

@mjmeintjes I apologize for the delay in addressing this PR, but thanks again for your work!
